//
// use book_champions

//insert data
db.books.insertOne({
  title: 'The Fellowship of the Ring',
  authors: ['J.R.R. Tolkien'],
  publisher: 'Allen & Unwin',
  pageCount: 423,
  rating: 4.8,
  cover: 'fellowship-of-the-ring.jpg',
  isAvailable: true,
})

db.books.insertOne({
  title: "Harry Potter and the Philosopher's Stone",
  authors: ['J.K. Rowling'],
  publisher: 'Bloomsbury',
  pageCount: 223,
  rating: 4.7,
  cover: 'philosophers-stone.jpg',
  isAvailable: true,
})

// query
db.books.find()
db.books.find({ publisher: 'Bloomsbury' })
db.books.find({ rating: { $gt: 4.7 } })
db.books.find({ rating: { $gt: 4.7 } }, { title: 1, publisher: 1 })
db.books.find({ rating: { $gt: 4.7 } }, { title: 1, publisher: 1, _id: 0 })
db.books.find({ _id: ObjectId('65155fb42f53abe42bd53cee') }) //change the id according to the autogenerated value

//update
db.books.updateOne({ title: 'The Fellowship of the Ring' }, { $set: { title: 'The Lord of the Rings: The Fellowship of the Ring', isAvailable: false } })

//delete
db.books.deleteOne({ isAvailable: false })
